networks:
  client_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24

  server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.11.0/24

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - router
    ports:
      - "5430:5432"
    networks:
      - server_network

  server:
    working_dir: /app
    build:
      context: ./server
    cap_add:
      - NET_ADMIN
    environment:
      PROTOCOL: tcp
      HOST: 10.0.11.50
      PORT: 5555
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      ROUTER_IP: 10.0.11.2
    volumes:
      - server_data:/app
    depends_on:
      - postgres
      - router
    ports:
      - "5555:5555"
    networks:
      server_network:
        ipv4_address: 10.0.11.50

  router:
    build:
      context: ./router
    cap_add:
      - NET_ADMIN
    networks:
      client_network:
        ipv4_address: 10.0.10.2
      server_network:
        ipv4_address: 10.0.11.2

  client:
    working_dir: /app
    build:
      context: ./client
    cap_add:
      - NET_ADMIN
    environment:
      PROTOCOL: tcp
      HOST: 10.0.11.50
      PORT: 5555
      ROUTER_IP: 10.0.10.2
    volumes:
      - client_data:/app
    depends_on:
      - router
    ports:
      - "5557:5555"
    networks:
      - client_network

volumes:
  postgres_data:
  server_data:
  router_data:
  client_data:
