networks:
  client_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${CLIENT_NETWORK}

  server_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SERVER_NETWORK}

services:
  router:
    build:
      context: ./router
    cap_add:
      - NET_ADMIN
    environment:
      CLIENT_NETWORK: ${CLIENT_NETWORK}
      SERVER_NETWORK: ${SERVER_NETWORK}
      ROUTER_CLIENT_IP: ${ROUTER_CLIENT_IP}
      ROUTER_SERVER_IP: ${ROUTER_SERVER_IP}
      PROXY_CLIENT_IP: ${PROXY_CLIENT_IP}
      PROXY_SERVER_IP: ${PROXY_SERVER_IP}
    networks:
      client_network:
        ipv4_address: ${ROUTER_CLIENT_IP}
      server_network:
        ipv4_address: ${ROUTER_SERVER_IP}

  mcproxy:
    build:
      context: ./router
    cap_add:
      - NET_ADMIN

    environment:
      CLIENT_NETWORK: ${CLIENT_NETWORK}
      SERVER_NETWORK: ${SERVER_NETWORK}
      ROUTER_CLIENT_IP: ${ROUTER_CLIENT_IP}
      ROUTER_SERVER_IP: ${ROUTER_SERVER_IP}
      PROXY_CLIENT_IP: ${PROXY_CLIENT_IP}
      PROXY_SERVER_IP: ${PROXY_SERVER_IP}
    networks:
      client_network:
        ipv4_address: ${PROXY_CLIENT_IP}
      server_network:
        ipv4_address: ${PROXY_SERVER_IP}

  server1:
    working_dir: /app
    build:
      context: ./server
    cap_add:
      - NET_ADMIN
    environment:
      ROUTER_IP: ${PROXY_SERVER_IP}
    volumes:
      - server_data:/app
    depends_on:
      - router
    ports:
      - "10500:10000"
      - "15500:5678"
    networks:
      - server_network

  server2:
    working_dir: /app
    build:
      context: ./server
    cap_add:
      - NET_ADMIN
    environment:
      ROUTER_IP: ${PROXY_SERVER_IP}
    volumes:
      - server_data:/app
    depends_on:
      - router
    ports:
      - "10501:10000"
      - "15501:5678"
    networks:
      - server_network
  
  server3:
    working_dir: /app
    build:
      context: ./server
    cap_add:
      - NET_ADMIN
    environment:
      ROUTER_IP: ${PROXY_SERVER_IP}
    volumes:
      - server_data:/app
    depends_on:
      - router
    ports:
      - "10502:10000"
      - "15502:5678"
    networks:
      - server_network

  server4:
    working_dir: /app
    build:
      context: ./server
    cap_add:
      - NET_ADMIN
    environment:
      ROUTER_IP: ${PROXY_SERVER_IP}
    volumes:
      - server_data:/app
    depends_on:
      - router
    ports:
      - "10503:10000"
      - "15503:5678"
    networks:
      - server_network

  client1:
    working_dir: /app
    build:
      context: ./client
    cap_add:
      - NET_ADMIN
    environment:
      ROUTER_IP: ${ROUTER_CLIENT_IP}
    volumes:
      - client_data:/app
    depends_on:
      - router
    ports:
      - "10600:10000"
      - "11600:5678"
    networks:
      - client_network

  client2:
    working_dir: /app
    build:
      context: ./client
    cap_add:
      - NET_ADMIN
    environment:
      ROUTER_IP: ${ROUTER_CLIENT_IP}
    volumes:
      - client_data:/app
    depends_on:
      - router
    ports:
      - "10601:10000"
      - "11601:5678"
    networks:
      - client_network

volumes:
  server_data:
  router_data:
  client_data:
