networks:
  client_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24

  server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.11.0/24

services:
  server1:
    working_dir: /app
    build:
      context: ./server
    cap_add:
      - NET_ADMIN
    environment:
      PROTOCOL: tcp
      HOST: 10.0.11.50
      PORT: 5555
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ROUTER_IP: 10.0.11.2
    volumes:
      - server_data:/app
    depends_on:
      - router
    ports:
      - "5555:5555"
    networks:
      server_network:
        ipv4_address: 10.0.11.50

  server2:
    working_dir: /app
    build:
      context: ./server
    cap_add:
      - NET_ADMIN
    environment:
      PROTOCOL: tcp
      HOST: 10.0.11.51
      PORT: 5555
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ROUTER_IP: 10.0.11.2
    volumes:
      - server_data:/app
    depends_on:
      - router
    ports:
      - "5556:5556"
    networks:
      server_network:
        ipv4_address: 10.0.11.51

  # server3:
  #   working_dir: /app
  #   build:
  #     context: ./server
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     PROTOCOL: tcp
  #     HOST: 10.0.11.52
  #     PORT: 5555
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     ROUTER_IP: 10.0.11.2
  #   volumes:
  #     - server_data:/app
  #   depends_on:
  #     - router
  #   ports:
  #     - "5557:5557"
  #   networks:
  #     server_network:
  #       ipv4_address: 10.0.11.52

  router:
    build:
      context: ./router
    cap_add:
      - NET_ADMIN
    networks:
      client_network:
        ipv4_address: 10.0.10.2
      server_network:
        ipv4_address: 10.0.11.2

  client1:
    working_dir: /app
    build:
      context: ./client
    cap_add:
      - NET_ADMIN
    environment:
      PROTOCOL: tcp
      HOST: 10.0.11.50
      PORT: 5555
      ROUTER_IP: 10.0.10.2
    volumes:
      - client_data:/app
    depends_on:
      - router
    ports:
      - "5558:5555"
    networks:
      - client_network

  client2:
    working_dir: /app
    build:
      context: ./client
    cap_add:
      - NET_ADMIN
    environment:
      PROTOCOL: tcp
      HOST: 10.0.11.51
      PORT: 5555
      ROUTER_IP: 10.0.10.2
    volumes:
      - client_data:/app
    depends_on:
      - router
    ports:
      - "5559:5556"
    networks:
      - client_network

volumes:
  server_data:
  router_data:
  client_data:
