networks:
  client_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${CLIENT_NETWORK}

  server_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SERVER_NETWORK}

services:
  server1:
    working_dir: /app
    build:
      context: ./server
    cap_add:
      - NET_ADMIN
    environment:
      ROUTER_IP: ${ROUTER_SERVER_IP}
    volumes:
      - server_data:/app
    depends_on:
      - router
    ports:
      - "5555:10000"
    networks:
      - server_network

  server2:
    working_dir: /app
    build:
      context: ./server
    cap_add:
      - NET_ADMIN
    environment:
      ROUTER_IP: ${ROUTER_SERVER_IP}
    volumes:
      - server_data:/app
    depends_on:
      - router
    ports:
      - "5556:10000"
    networks:
      - server_network

  router:
    build:
      context: ./router
    cap_add:
      - NET_ADMIN
    networks:
      client_network:
        ipv4_address: ${ROUTER_CLIENT_IP}
      server_network:
        ipv4_address: ${ROUTER_SERVER_IP}

  mcproxy:
    build:
      context: ./router
    cap_add:
      - NET_ADMIN
    networks:
      client_network:
        ipv4_address: ${PROXY_CLIENT_IP}
      server_network:
        ipv4_address: ${PROXY_SERVER_IP}

  client1:
    working_dir: /app
    build:
      context: ./client
    cap_add:
      - NET_ADMIN
    environment:
      ROUTER_IP: ${ROUTER_CLIENT_IP}
    volumes:
      - client_data:/app
    depends_on:
      - router
    ports:
      - "5560:10000"
    networks:
      - client_network

  client2:
    working_dir: /app
    build:
      context: ./client
    cap_add:
      - NET_ADMIN
    environment:
      ROUTER_IP: ${ROUTER_CLIENT_IP}
    volumes:
      - client_data:/app
    depends_on:
      - router
    ports:
      - "5561:10000"
    networks:
      - client_network

volumes:
  server_data:
  router_data:
  client_data:
